#!/bin/bash
IBM_ID=$1
IBM_PASSWORD=$2

for str in $(cat versions.csv | grep -v \#); do
IFS=\| read -ra ary <<<"$str";
VERSION=${ary[0]}
REPO=${ary[1]}
PRODUCTID=${ary[2]}
JDK=${ary[3]}
docker run --rm -v $(pwd):/host:Z ibm-im /host/install_was $VERSION $IBM_ID $IBM_PASSWORD $PRODUCTID $REPO $JDK || exit $?
done
