#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 3 ]; then
  echo "Usage: build <version> <IBMid> <IBMid password>"
  exit 1
fi

docker build -t installation-manager im || exit $?
docker run --rm -v $(pwd):/host installation-manager /host/install_was $1 $2 $3 || exit $?
docker build -t websphere-traditional:install install || exit $?
docker build -t websphere-traditional:profile profile || exit $?
