#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 2 ]; then
  echo "Usage: build_all <IBMid> <IBMid password>"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while read line; do
  if [[ $line == \#* ]]; then continue; fi
  version=$(cut -d, -f1 <<< $line)
  log_file="build-${version}.log"
  echo "Building ${version} - outputing logs to ${log_file}"
  $DIR/build ${version} $1 $2 &> build-${version}.log
  if [ $? == 0 ]; then
    docker tag websphere-traditional:install websphere-traditional:${version}-install
    docker tag websphere-traditional:profile websphere-traditional:${version}-profile
    echo "Successfully built websphere-traditional:${version}-install and websphere-traditional:${version}-profile"
  else
    echo "Build failed - see build-${version}.log"
  fi
done < versions.csv
