#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 1 ]; then
  echo "Usage: push_all <[repository:port/]namespace>"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NAMESPACE=$1

push()
{
  from_name=$1
  to_name=$2
  echo "*** Pushing $from_name to $to_name ***"
  docker tag $from_name $to_name
  docker push $to_name
  docker rmi $to_name
}

push_to_namespace()
{
  from_name=$1
  namespace=$2
  to_name="$namespace/$from_name"
  push $from_name $to_name
}  

while read line; do
  if [[ $line == \#* ]]; then continue; fi
  version=$(cut -d, -f1 <<< $line)
  prefix="websphere-traditional:${version}-"
  for suffix in "install" "profile"; do
    name="${prefix}${suffix}"
    push_to_namespace $name $NAMESPACE
 done
done < $DIR/versions.csv

push "websphere-traditional:${version}-install" "$NAMESPACE/websphere-traditional:install"
push "websphere-traditional:${version}-profile" "$NAMESPACE/websphere-traditional:profile"
push "websphere-traditional:${version}-profile" "$NAMESPACE/websphere-traditional:latest"
