#!/bin/bash
#
###########################################################################
# (C) Copyright IBM Corporation 2016.                                     #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#      http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
###########################################################################

if [ $# != 3 ]; then
  echo "Usage: build <IBMid> <IBMid password> <IM download url>"
  exit 1
fi

IBM_ID=$1
IBM_PASSWORD=$2
IM_URL=$3

docker build -t websphere-traditional:profile --build-arg IBMID=$IBM_ID --build-arg IBMID_PWD=$IBM_PASSWORD --build-arg IMURL="$IM_URL" . || exit $?
